openapi: '3.0.0'
info:
  version: '1.0.0'
  title: Electronics Inventory
  description: Electronics Inventory is a full-stack web-app project where users can keep track of an electronics lab inventory. With thousands of small components its easy to lose track of where and how many of each part you currently have in stock. With this website you have full control over you inventory, from anywhere in the world. In order to use this website, you must have an account. This project was coded from scratch by myself as a capstone project for my career change into Software Engineering.
  license:
    name: MIT
    url: https://github.com/joshl26/electronics-inventory-backend/blob/master/LICENSE
  contact:
    name: Joshua Lehman
    url: https://joshlehman.ca
    email: joshlehman.dev@gmail.com
servers:
  - url: https://electronics-inventory-server.onrender.com
  - url: http://localhost:3500/
tags:
  - name: Auth
    description: Electronics Inventory auth
  - name: Login
    description: Electronics Inventory login
  - name: Logout
    description: Electronics Inventory logout
  - name: Parts
    description: Electronics Inventory parts
  - name: Root
    description: Electronics Inventory root
  - name: Users
    description: Electronics Inventory users
paths:
  /:
    get:
      tags:
        - Root
      summary: Refresh the root homepage
      description: Refresh the root homepage
      operationId: refreshRoot
      responses:
        '200':
          description: Only returns 200
  /auth:
    post:
      tags:
        - Auth
      summary: Login existing user
      description: Login existing user
      operationId: loginUser
      responses:
        '200':
          description: User login approved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        404:
          description: No user found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/refresh:
    get:
      tags:
        - Auth
      summary: Refresh the user auth
      description: Refresh the user auth
      operationId: refreshUserAuth
      responses:
        '200':
          description: Only returns 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
            application/xml:
              schema:
                $ref: '#/components/schemas/Users'
  /auth/logout:
    post:
      tags:
        - Auth
      summary: Logout user
      description: Logout user
      operationId: logoutUser
      responses:
        '200':
          description: User logout approved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        404:
          description: No user found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /notes:
    get:
      tags:
        - Notes
      summary: Get all notes from DB
      description: Return all notes in the database
      responses:
        '200':
          description: The page displaying a list of all the currrent notes in the DB
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/Notes'
        404:
          description: No notes found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Notes
      summary: Insert a new note record in the database
      description: Insert a new note record in the database
      operationId: addNewNote
      requestBody:
        description: Create a new note record in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notes'
          application/xml:
            schema:
              $ref: '#/components/schemas/Notes'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Notes'
        required: true
      responses:
        '200':
          description: Insert a new note record in the database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notes'
        404:
          description: No notes found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - Notes
      summary: Update note details
      description: This can only be done by a user that is logged in
      operationId: updateNote
      requestBody:
        description: Update an existing note in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notes'
          application/xml:
            schema:
              $ref: '#/components/schemas/Notes'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Notes'
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid note id in req body
        '404':
          description: Note not found
    delete:
      tags:
        - Notes
      summary: Delete note record from DB
      description: Delete note record from DB
      operationId: deleteNote
      responses:
        '400':
          description: Invalid note id in req body
        '404':
          description: Note not found

  /parts:
    get:
      tags:
        - Parts
      summary: Get all parts from DB
      description: Return all parts in the database
      responses:
        '200':
          description: The page displaying a list of all the currrent notes in the DB
          content:
            text/html:
              schema:
                type: string
        404:
          description: No notes found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Parts
      summary: Insert a new part record in the database
      description: Insert a new part record in the database
      operationId: addNewPart
      requestBody:
        description: Create a new part record in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parts'
          application/xml:
            schema:
              $ref: '#/components/schemas/Parts'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Parts'
        required: true
      responses:
        '200':
          description: Insert a new part record in the database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parts'
        404:
          description: No parts found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - Parts
      summary: Update part details
      description: This can only be done by a user that is logged in with the correct role
      operationId: updatePart
      requestBody:
        description: Update an existing part in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parts'
          application/xml:
            schema:
              $ref: '#/components/schemas/Parts'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Parts'
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid part id in req body
        '404':
          description: Part not found
    delete:
      tags:
        - Parts
      summary: Delete part record from DB
      description: Delete part record from DB
      operationId: deletePart
      responses:
        '400':
          description: Invalid part id in req body
        '404':
          description: Part not found
  /users:
    get:
      tags:
        - Users
      summary: Get all users from DB
      description: Return all users in the database
      responses:
        '200':
          description: The page displaying a list of all the currrent users in the DB
          content:
            text/html:
              schema:
                type: string
        404:
          description: No users found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Users
      summary: Insert a new users record in the database
      description: Insert a new user record in the database
      operationId: addNewUser
      requestBody:
        description: Create a new user record in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
          application/xml:
            schema:
              $ref: '#/components/schemas/Users'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Users'
        required: true
      responses:
        '200':
          description: Insert a new user record in the database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        404:
          description: No parts found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - Users
      summary: Update user details
      description: This can only be done by a user that is logged in with the correct role
      operationId: updateUser
      requestBody:
        description: Update an existing user in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
          application/xml:
            schema:
              $ref: '#/components/schemas/Users'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Users'
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid user id in req body
        '404':
          description: User not found
    delete:
      tags:
        - Users
      summary: Delete user record from DB
      description: Delete user record from DB
      operationId: deleteUser
      responses:
        '400':
          description: Invalid user id in req body
        '404':
          description: User not found
  /login:
    get:
      tags:
        - Login
      summary: Return login user HTML page
      description: Return login user HTML page
      operationId: loginNewUserForm
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
            application/xml:
              schema:
                $ref: '#/components/schemas/Users'
    post:
      tags:
        - Login
      summary: Login user
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
            application/xml:
              schema:
                $ref: '#/components/schemas/Users'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username: # <!--- form field name
                  type: string
                password: # <!--- form field name
                  type: string
              required:
                - username
                - password
  /logout:
    get:
      tags:
        - Logout
      summary: Return logout user HTML page
      description: Return logout user HTML page
      operationId: logoutNewUserForm
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
            application/xml:
              schema:
                $ref: '#/components/schemas/Users'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
components:
  schemas:
    Notes:
      type: object
      required:
        - user
        - title
        - text
      properties:
        _id:
          type: string
          format: uuid
          description: The unique id auto generated by mongoose for the note when it was created
        user:
          type: string
          format: uuid
          description: The username of the note
        title:
          type: string
          format: text
          description: The title of the note
        text:
          type: string
          format: text
          description: The text of the note
        completed:
          type: boolean
          description: Note completed flag
        createdAt:
          type: string
          format: Date/Time
          description: Date/Time Note created
        updatedAt:
          type: string
          description: Date/Time Note updated
        ticket:
          type: number
          description: Ticket number for note
        __V:
          type: number
          format: int32
          description: Version of the note, starting at 0 and incremented by +1 with each change saved
    Parts:
      type: object
      required:
        - user
        - name
        - description
      properties:
        _id:
          type: string
          format: uuid
          description: The unique id auto generated by mongoose for the part
        user:
          type: string
          format: uuid
          description: The unique id auto generated by mongoose for the user
        name:
          type: string
          description: The name of the part
        description:
          type: string
          description: The description of the part
        qty:
          type: number
          description: The inventory stock qty of the part
        partType:
          type: string
          description: The type of the part
        createdAt:
          type: string
          format: Date/Time
          description: Date/Time Note created
        updatedAt:
          type: string
          format: Date/Time
          description: Date/Time Note updated
        ticket2:
          type: number
          description: Ticket number for note
        __V:
          type: number
          format: int32
          description: Version of the note, starting at 0 and incremented by +1 with each change saved
        images:
          type: array
          description: Array of image objects
          items:
            type: object
            properties:
              _id:
                type: string
                format: uuid
                description: The id auto generated by mongoose for the campground
              url:
                type: string
                format: uri
                description: The url of the image
              filename:
                type: string
                description: The filename of the image
        partNumber:
          type: string
          description: The part number of the part
        serialNumber:
          type: string
          description: The serial number of the part
        manufacturer:
          type: string
          description: The manufacturer of the part
        updatedBy:
          type: string
          description: The name of the user that last updated the part
        mfgDate:
          type: string
          description: The manufacturing date of the part
        backorder:
          type: number
          description: The backorder qty of the part
        vendorName:
          type: string
          description: The vendor name of the part
        partPackage:
          type: string
          description: The package type of the part
        partLocation:
          type: string
          description: The location of the part
        deletedImages:
          type: array
          description: Array of image objects
          items:
            type: object
            properties:
              _id:
                type: string
                format: uuid
                description: The id auto generated by mongoose for the campground
              url:
                type: string
                format: uri
                description: The url of the image
              filename:
                type: string
                description: The filename of the image
        cost:
          type: number
          description: The cost of the part
        createdBy:
          type: string
          description: The name of the user of that created the part
    Users:
      type: object
      required:
        - username
        - password
      properties:
        _id:
          type: string
          format: uuid
          description: The unique id auto generated by mongoose for the user
        username:
          type: string
          description: The username of the user
        password:
          type: string
          description: The username of the user
        roles:
          type: array
          description: Array of roles for this user
          items:
            type: object
            properties:
              role:
                type: string
                description: The role of the user
        __V:
          type: number
          format: int32
          description: Version of the user settings, starting at 0 and incremented by +1 with each change saved
        colorMode:
          type: string
          description: The colorMode of the User
        partsListView:
          type: string
          description: The style of tables selected by user
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []
