const express = require("express");
const router = express.Router();
const notesController = require("../controllers/notesController");
const verifyJWT = require("../middleware/verifyJWT");

/**
 * @swagger
 *  components:
 *   schemas:
 *    Notes:
 *      type: object
 *      required:
 *      - user
 *      - title
 *      - text
 *      properties:
 *          _id:
 *             type: string
 *             format: uuid
 *             description: The unique id auto generated by mongoose for the note
 *          user:
 *             type: string
 *             format: uuid
 *             description: The username of the note
 *          title:
 *              type: string
 *              description: The title of the note
 *          text:
 *              type: string
 *              description: The text of the note
 *          completed:
 *              type: boolean
 *              description: Note completed flag
 *          createdAt:
 *              type: date
 *              description: Date/Time Note created
 *          updatedAt:
 *              type: date
 *              description: Date/Time Note updated
 *          ticket:
 *              type: number
 *              description: Ticket number for note
 *          __V:
 *              type: number
 *              format: int32
 *              description: Version of the note, starting at 0 and incremented by +1 with each change saved
 *
 */

/**
 * @swagger
 * /notes/:
 *   get:
 *     tags:
 *     - Notes
 *
 */

/**
 * @swagger
 * /notes/:
 *   get:
 *     summary: Get all notes from DB
 *     description: Return all notes in database
 *     responses:
 *       200:
 *         description: List of notes
 */

/**
 * @swagger
 * /notes/:
 *   post:
 *     tags:
 *     - Notes
 *
 */

/**
 * @swagger
 * /notes/:
 *   post:
 *     summary: Create new note
 *     description: Create new note
 *     responses:
 *       200:
 *         description: Create new note
 */

/**
 * @swagger
 * /notes/:
 *   patch:
 *     tags:
 *     - Notes
 *
 */

/**
 * @swagger
 * /notes/:
 *   patch:
 *     summary: Update note details
 *     description: Update note details
 *     responses:
 *       200:
 *         description: Update note details
 */

/**
 * @swagger
 * /notes/:
 *   delete:
 *     tags:
 *     - Notes
 *
 */

/**
 * @swagger
 * /notes/:
 *   delete:
 *     summary: Delete note
 *     description: Delete note
 *     responses:
 *       200:
 *         description: Delete note
 */

router.use(verifyJWT);

router
  .route("/")
  .get(notesController.getAllNotes)
  .post(notesController.createNewNote)
  .patch(notesController.updateNote)
  .delete(notesController.deleteNote);

module.exports = router;
