const express = require("express");
const router = express.Router();
const usersController = require("../controllers/userController");
const verifyJWT = require("../middleware/verifyJWT");

/**
 * @swagger
 *  components:
 *   schemas:
 *    Users:
 *      type: object
 *      required:
 *      - username
 *      - password
 *      properties:
 *          _id:
 *             type: string
 *             format: uuid
 *             description: The unique id auto generated by mongoose for the user
 *          username:
 *              type: string
 *              description: The username of the user
 *          password:
 *              type: string
 *              description: The username of the user
 *          roles:
 *              type: array
 *              description: Array of roles for this user
 *              items:
 *                  type: object
 *                  properties:
 *                      role:
 *                          type: string
 *                          description: The role of the user
 *          __V:
 *              type: number
 *              format: int32
 *              description: Version of the user settings, starting at 0 and incremented by +1 with each change saved
 *          colorMode:
 *              type: string
 *              description: The colorMode of the User
 *          partsListView:
 *              type: string
 *              description: The style of tables selected by user
 *
 */

/**
 * @swagger
 * /users/:
 *   get:
 *     tags:
 *     - Users
 *
 */

/**
 * @swagger
 * /users/:
 *   get:
 *     summary: Get all users from DB
 *     description: Return all users in database
 *     responses:
 *       200:
 *         description: List of users
 */

/**
 * @swagger
 * /users/:
 *   post:
 *     tags:
 *     - Users
 *
 */

/**
 * @swagger
 * /users/:
 *   post:
 *     summary: Create new user
 *     description: Create new user
 *     responses:
 *       200:
 *         description: Create new user
 */

/**
 * @swagger
 * /users/:
 *   patch:
 *     tags:
 *     - Users
 *
 */

/**
 * @swagger
 * /users/:
 *   patch:
 *     summary: Update user details
 *     description: Update user details
 *     responses:
 *       200:
 *         description: Update user details
 */

/**
 * @swagger
 * /users/:
 *   delete:
 *     tags:
 *     - Users
 *
 */

/**
 * @swagger
 * /users/:
 *   delete:
 *     summary: Delete user
 *     description: Delete user
 *     responses:
 *       200:
 *         description: Delete user
 */

router.use(verifyJWT);
router
  .route("/")
  .get(usersController.getAllUsers)
  .post(usersController.createNewUser)
  .patch(usersController.updateUser)
  .delete(usersController.deleteUser);

module.exports = router;
